### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mpeyper** [testing-library/react-hooks-testing-library#19]
The example in the README is very basic (by design) but there have been numerous queries recently about more advanced usage so I think it's time we expand the documentation to cover these.

Initially, this could be part of the README, but I'd prefer keeping the README fairly light and having a `docs` directory that can explain features, concepts and techniques in more details (a `.md` file per topic).

We could look at generating a [`gitbook`](https://www.gitbook.com/), [`docusaurus`](https://docusaurus.io/), [`docz`](https://www.docz.site/) or whatever the documentation site flavour of the month is from these docs at some point in the future (unless anyone want to set this up now).

Another thing that I am aware of ([from experience](https://ioof-holdings.github.io/redux-subspace/) 😞) is that docs written by the author are often not very useful to users (especially new users), as there is so much implied understanding that gets baked in.  That's why I'm asking for help for others to write these docs.  Include any gotchas or hiccups you hit along the way.

It doesn't have to be completely comprehensive from the get-go and we can improve and expand them as we go, so any and all contributions are welcome towards them.

Topics to cover:

- [x] when you should use this library
- [x] when you should *NOT* use this library
- [x] usage of `wrapper` (`renderHook` option)
  - [x] [context providers](#23)
- [x] usage of `initialProps` (`renderHook` option) and the `newProps` (`rerender` parameter)
  - [x] dynamic props
  - [x] memoization
- [x] usage of `waitForNextUpdate`
  - [x] async hooks
  - [x] suspence
  - [x] [warnings](https://github.com/mpeyper/react-hooks-testing-library/issues/14)
- [x] error handling
- [ ] recipies 
  - [ ] common hook patterns (if there are any?)
  - [ ] setup with different test runners
- [ ] examples
- [ ] troubleshooting
  - [x] ~[dom errors](https://github.com/mpeyper/react-hooks-testing-library/issues/17)~ (no more dom to cause errors (#40)
  - [ ] [result not changing](https://github.com/mpeyper/react-hooks-testing-library/issues/18)
- [x] FAQ
  - [x] [why do I need `.current`?](https://github.com/mpeyper/react-hooks-testing-library/issues/3)
- [x] API

There probably more that can also be included so feel free to go with want makes sense to you.  I'm happy to update the checklist if you want to make suggestions in the comments here.

**_Note: I'm marking these off as we go, but that does not mean what is shown in the [work-in-progress site](https://react-hooks-testing-library.netlify.com/) as at all the final version and/or closed to improvements._**

**Comment by mpeyper** [comment]
I've made a start on this.  You can see the work-in-progress docs [here](https://react-hooks-testing-library.netlify.com/).  I decided to go with [docz](https://www.docz.site/) and so far it's been pretty great.  [netlify](https://app.netlify.com/) has also been pretty nice for the deployment of the site.

If you want to help and contribute some documentation, the branch is [called `better-docs`](https://github.com/mpeyper/react-hooks-testing-library/tree/better-docs).

**Comment by mpeyper** [comment]
These docs have been released as the official docs now, but still with some "coming soon" pages.  I'll leave this open to track any improvements that we want to make to them.

There has also been a suggestion that the current theme (Docz dark theme) is not particularly readable (#107).  I've been looking into it the theming for Docz looks a bit, but it's quite fiddly.  I'm thinking about just switching to the light theme (in the short term?) or maybe looking at an alternative site generator ([`docusaurus`](https://docusaurus.io/) looks pretty cool).

**Comment by mpeyper** [comment]
I'm closing this now as the docs have been switched back to the light theme and the "Coming soon" pages have been removed (analytics showed that they were very rarely (like < 5) hit.  Happy if someone wants to add them back with some content, but I'm not going to worry.
